version: 2.1

# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_test:
    # https://circleci.com/docs/2.0/executor-types/
    # https://circleci.com/developer/images/image/cimg/python
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: install packages
          command: |
            pip install --user --no-cache-dir -r requirements.txt
      - run:
          name: Run tests
          command: pytest

  build_push_docker_image:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: install packages 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt          
      - setup_remote_docker
      - run: |
          TAG=0.1.<< pipeline.number >>
          docker build -t $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$TAG

workflows:
  test_build_deploy:
    jobs:
      - build_test
      - build_push_docker_image:
          requires:
            - build_test