version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2

# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_test:
    # https://circleci.com/docs/2.0/executor-types/
    # https://circleci.com/developer/images/image/cimg/python
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample:
    jobs:
      - build_test
