version: 2.1

orbs: 
  heroku: circleci/heroku@1.2.6

jobs:
  build_test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: install packages
          command: |
            pip install --user --no-cache-dir -r requirements.txt
          when: always
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run Linting
          command: flake8 --ignore=F841

  build_push_docker_image:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout   
      - setup_remote_docker
      - run: |
          TAG=$CIRCLE_SHA1
          docker build -t $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME .
          docker build -t $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          docker push $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:$TAG

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
      - run: |
          heroku run python manage.py migrate -a $HEROKU_APP_NAME
          heroku run python manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL --password $DJANGO_SUPERUSER_PASSWORD -a $HEROKU_APP_NAME
          heroku run python manage.py loaddata dumps/data.json -a $HEROKU_APP_NAME
          
workflows:
  test_build_deploy:
    jobs:
      - build_test
      - build_push_docker_image:
          requires:
            - build_test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build_push_docker_image
          filters:
            branches:
              only: master
