version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/docker@1.5.0

# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_test:
    # https://circleci.com/docs/2.0/executor-types/
    # https://circleci.com/developer/images/image/cimg/python
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: install packages
          command: |
            pip install --user --no-cache-dir -r requirements.txt
      - run:
          name: Run tests
          command: pytest

  build_push_docker_image:
      docker:
        - image: circleci/python:3.9
      steps:
        - checkout
        - run:
            name: Install packages
            command: |
              pip install --user --no-cache-dir -r requirements.txt
        - setup_remote_docker
        - docker/check
        - docker/build:
            image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
            extra_build_args: "-t $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME"
            tag: 0.1.<< pipeline.number >>             
        - docker/push:
            image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
            tag: "latest"
        - docker/push:
            image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
            tag: "0.1.<< pipeline.number >>"

workflows:
  test_build_deploy:
    jobs:
      - build_test
      - build_push_docker_image:
          requires:
            - build_test